window.VIDEO_EDITOR_TRANSLATIONS = {
  VIDEOS: 'Videos',
  PROJECT_IS_NOT_FINISHED_YET: 'Project is not finished yet',
  MISSING_MUSIC_DESCRIPTION:
    'Please upload and/or select your music track in the music section in order to export your video',
  ADD_MUSIC: 'Add Music',
  OH_WAIT: 'Oh, wait...',
  MUSIC_IS_MISSING: 'Music is missing !',
  MISSING_MUSIC_REQUIRED_DESCRIPTION:
    'Our AI has chosen great music for your project',
  SKIP: 'Skip',
  APPLY: 'Apply',
  PRIMARY_FONT: 'Primary',
  SECONDARY_FONT: 'Secondary',
  MALE: 'Male',
  FEMALE: 'Female',
  RECORDING_DURATION: 'Recording duration',
  MY_VOICEOVERS: 'My voiceovers',
  CANCEL: 'Cancel',
  GOT_IT: 'Got it!',
  AI_VOICEOVER: 'AI Voiceover',
  RECORD: 'Record',
  UPLOAD: 'Upload',
  MY_MUSIC: 'My music',
  MUSIC_LIBRARY: 'Music library',
  DRAG_AND_DROP_A_FILE_OR_USE_UPLOAD_BUTTON:
    'Drag and drop a file or use “Upload” button',
  STOP: 'Stop',
  RECORDING: 'Recording',
  SAVE: 'Save',
  SELECT: 'Select',
  RETAKE: 'Retake',
  MUSIC: 'Music',
  CHARACTERS: 'characters',
  VOICEOVER: 'Voiceover',
  FINALIZE_YOUR_VIDEO_BEFORE_EXPORT: 'Finalize your video before export',
  MISSING_VIDEOS:
    'Please, fill in the missing video placeholder(s) on these scenes',
  MISSING_IMAGES:
    'Please, fill in the missing image placeholder(s) on these scenes',
  EXPORT_ANYWAY: 'Export Anyway',
  EDIT_SCENES: 'Edit Scenes',
  CLOSE: 'Close',
  OK_CLOSE: 'OK, close',
  EDIT_PROJECT_WARNING_POPUP_DESCRIPTION:
    'You have not made any changes to project, please edit project before previewing or exporting.',
  TEXT_TO_SPEECH: 'Text to Speech',
  CONVERT_TEXT_TO_AUDIO: 'Convert your text into a high quality audio',
  SAMPLE_OF_VOICES: 'Samples of available voices',
  SUBSCRIBE_FOR_BENEFITS:
    'Subscribe to use this feature and enjoy other benefits by Renderforest',
  PKG_START_FROM: 'Get your package starting from',
  GENERATE: 'Generate',
  LOWER_THIRD_SETTINGS: 'Lower third settings',
  START: 'Start',
  END: 'End',
  MIN: 'min',
  SEC: 'sec',
  REMOVE: 'Remove',
  DUPLICATE: 'Duplicate',
  PALETTES: 'Palettes',
  CUSTOM: 'Custom',
  BACK: 'Back',
  IMPORT_FILE: 'Import file',
  CREATE_NEW: 'Create new',
  WATERMARK_FILE_INFO_TOOLTIP: 'Please, use 1920x1080 PNG transparent image.',
  MY_FILES: 'My files',
  MY_FILES_AI_IMAGE_GENERATOR: 'My files',
  LOGO_WATERMARK: 'Logo Watermark',
  TEXT_WATERMARK: 'Text Watermark',
  OR: 'OR',
  SECS_AGO: '%s secs ago',
  MINS_AGO: '%s mins ago',
  HRS_AGO: '%s hrs ago',
  DAYS_AGO: '%s days ago',
  MONTHS_AGO: '%s months ago',
  YEARS_AGO: '%s years ago',
  PREVIEW: 'Preview',
  CANCEL_PREVIEW: 'Cancel Preview',
  PROCEED: 'Proceed',
  VIDEO_DURATION: 'Video duration',
  VIDEO_MAX_DURATION: 'Video max duration',
  INCLUDE_TEMPLATE_SOUND_EFFECT: 'Include template sound effect',
  FONT_SCALE: 'Font scale',
  REPLACE: 'Replace',
  TYPE_YOUR_TEXT: 'Type your text',
  TEXT_POSITION: 'Text position',
  EDIT_TEXT: 'Edit text',
  LEFT: 'Left',
  RIGHT: 'Right',
  CENTER: 'center',
  CHARACTERS_ADVISED: 'characters advised',
  PNG_TYPE_WARNING_TEXT: 'Please, use 1920x1080 PNG transparent image.',
  DELETE_WATERMARK_WARNING_TEXT:
    'Are you sure to remove watermark from project?',
  DELETE: 'Delete',
  KEEP_WATERMARK: 'Keep it',
  WATERMARK: 'Watermark',
  START_DATE_EXCEED_END_DATE_ERR_MESSAGE:
    "Start date can't exceed the end date",
  END_DATE_EARLIEAR_THAN_START_DATE_ERR_MESSAGE:
    "End date can't be earlier than the start date",
  END_DATE_EXCEED_VIDEO_DURATION_ERR_MESSAGE:
    "End date can't exceed video duration (xx:yy)",
  SIMILAR_SCENES: 'Similar scenes',
  SIZE: 'Size',
  OPACITY: 'Opacity',
  TILE: 'Tile',
  SINGLE: 'Single',
  DONE: 'Done',
  POSITION: 'Position',
  MODE: 'Mode',
  MODEL: 'Model',
  PADDING: 'Padding',
  RENDERING: 'Rendering',
  ADD_MEDIA: 'Add media',
  STOCK_FOOTAGE: 'Stock footage',
  STOCK_IMAGE: 'Stock Image',
  EDIT: 'Edit',
  EDIT_MEDIA: 'Edit media',
  RECENTLY_USED: 'Recently used',
  ADD_TO_SCENE: 'Add to scene',
  RECOMMENDED: 'Recommended size %s',
  VOLUME: 'Volume',
  VIDEO: 'Video',
  YOUR_TEXT: 'Your text',
  FONT: 'Font',
  COLOR: 'Color',
  TEXT_COLOR: 'Text color',
  CUSTOM_COLORS: 'Custom colors',
  TEXT: 'Text',
  TRANSFORM: 'Transform',
  LOGO: 'Logo',
  SUGGEST_NEW_SCENE_BUTTON: 'Suggest new scene',
  SEARCH: 'Search',
  NO_SEARCH_RESULT_DESCRIPTION: 'Sorry, no results found for /%s/',
  SUGGEST_NEW_SCENE_TITLE: 'Suggest a new scene',
  SUGGEST_NEW_SCENE_DESCRIPTION: `Describe your idea in a couple of words and we will consider adding the
  requested scene to this template. Thanks!`,
  SUGGEST_NEW_SCENE_SUCCESS_CONTENT_TITLE: 'Thank you',
  SUGGEST_NEW_SCENE_SUCCESS_CONTENT_DESCRIPTION: 'Your suggestion is accepted',
  DURATION: 'Duration',
  DESELECT: 'Deselect',
  DESELECT_ALL: 'Deselect All',
  ADD_TO_VIDEO: 'Add to Video',
  START_CREATING_MESSAGE: 'Select one of the options to start creating',
  SELECT_SCENES: 'Select Scenes',
  SELECT_SCENES_DESCRIPTION:
    'Browse scenes and create Your project from scratch',
  CREATE_WITH_AI: 'Create with AI',
  CREATE_WITH_AI_DESCRIPTION:
    'Transform Your ideas, notes or script into AI-generated videos effortlessly',
  START_WITH_PRESETS: 'Start with Presets',
  CREATE_NEW_VIDEO: 'Create new video',
  WATCH_TUTORIAL: 'Watch Tutorial',
  EDIT_THIS_PRESET: 'Edit This Preset',
  INCLUDES_PREMIUM_SCENES: 'Includes premium scenes',
  ROTATE_LEFT: 'Rotate left',
  ROTATE_RIGHT: 'Rotate right',
  FIT: 'Fit',
  FILL: 'Fill',
  VOLUME_BALANCE: 'Volume balance',
  CURRENT_VIDEO: 'Current video',
  PROJECT_AUDIO: 'Project audio',
  RENDERFOREST_STOCK: 'Renderforest stock',
  POWERED_BY_UNSPLASH: 'Powered by %s',
  PHOTO_BY_AUTHOR: 'Photo by %s',
  USE: 'Use',
  ADD_TEXT: 'Add text',
  SCALE: 'Scale',
  ADJUST: 'Adjust',
  SATURATION: 'Saturation',
  BRIGHTNESS: 'Brightness',
  CONTRAST: 'Contrast',
  BACK_TO_TEMPLATE: 'Back to template',
  OOPS_NOTHING_HERE: 'Oops, nothing here',
  YES_DROP_IT: 'Yes, drop it!',
  ADD_TO_TIMELINE: 'Add to timeline',
  ALREADY_USED_AUDIO_PROJECT:
    'Sorry, this audio is already used in following projects.',
  REMOVE_SOUND_FROM_LIBRARY: 'This will remove the file from Library',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  UPLOAD_SESSION_EXPIRED: 'Upload session expired',
  UPLOAD_SESSION_EXPIRED_DESCRIPTION:
    'Your upload session has expired. Please scan the QR code again.',
  UNSUPPORTED_FILE_FORMAT:
    'It seems like the file is damaged or not supported type',
  SUPPORTED_FILE_TYPES_WARNING: 'Not supported. Please upload ',
  ADD_AUDIO: 'Add audio',
  TYPE_YOUR_TEXT_HERE: 'Type your text here',
  AI_RECORD_LEAVING:
    'AI record is unsaved Do you want to leave without saving record?',
  LEAVE: 'Leave',
  STAY: 'Stay',
  AI_RECORD_WILL_BE_LOST: 'Unsaved record will be lost',
  GENERATED_VOICEOVER: 'Generated voiceover',
  ADD: 'Add',
  SUBSCRIBE: 'Subscribe',
  LANGUAGE: 'Language',
  IDEA_TO_VIDEO: 'Idea to Video',
  SCRIPT_TO_VIDEO: 'Script to Video',
  DO_MAGIC: 'Do Magic',
  NEXT: 'Next',
  ALL: 'All',
  PHOTO: 'Photo',
  SUBMIT: 'Submit',
  NO_INTERNET_CONNECTION:
    'Looks like You went offline. Please, check Your connection and try again.',
  FULL_STORAGE_WARNING:
    'You have reached maximum size of your library. To upload more files, please, upgrade your plan or remove some files from library.',
  UPGRADE: 'Upgrade',
  UPLOAD_FONT: 'Upload font',
  UPLOADING: 'Uploading',
  UPLOADED: 'Uploaded',
  UPLOAD_FAILED: 'Upload failed',
  CONTACT: 'Contact',
  FONT_UPLOAD_LIMIT_REACHED_TITLE:
    'Sorry, you have reached the font upload limit',
  FONT_UPLOAD_LIMIT_REACHED_DESCRIPTION:
    'You can delete unused fonts or contact support if you have suggestions',
  FAST_PREVIEW: 'Fast preview',
  FREE_EXPORT: 'Free export',
  HD720: 'HD 720',
  UHD4K: 'UHD 4K',
  HD1080: 'HD 1080',
  EXPORT_YOUR_VIDEO_IN_LOW_QUALITY: 'Export your video in low quality',
  EXPORT_YOUR_VIDEO_IN_UHD4K_QUALITY: 'Export your video in UHD4K quality',
  EXPORT_YOUR_VIDEO_IN_HD1080_QUALITY: 'Export your video in HD1080 quality',
  EXPORT_YOUR_VIDEO_IN_HD720_QUALITY: 'Export your video in HD720 quality',
  EXPORT_VIDEO_WITH_FAST_PREVIEW_TO_SAVE_TIME:
    'Export video with fast preview to save time',
  WARNING: 'Warning',
  FILTER: 'Filter',
  DURATION_LIMIT:
    'Your current plan allows to create up to %s minute of videos.',
  REPLACE_PREMIUM_SCENES: 'Replace premium scenes',
  LOW_QUALITY: 'Low Quality',
  UNLIMITED_4K: 'Unlimited <4K UHD> videos within a month',
  PER_MONTH: ' / Per month',
  LIST_OF_AVAILABLE_FONTS: 'List of available fonts',
  UP_TO: 'up to %s',
  MONTHLY: 'monthly',
  SEE_OTHER_PLANS: 'See other plans',
  YEAR: '%s / year',
  UNLIMITED_DURATION: '<Unlimited> video duration',
  NO_WATERMARK_: '<No> watermarks or ads',
  STORAGE: '<%s> storage',
  PREMIUM_WEBSITE: '%s Premium website',
  UNLIMITED_FONT: '<Unlimited> font uploads',
  MOST_POPULAR: 'Most Popular',
  YEARLY: 'yearly',
  CREATED_VIDEOS_LIMIT_MESSAGE:
    'Your current account allows to create up to %s videos',
  SUBSCRIBE_AND_ENJOY: 'Subscribe and enjoy creating without limits',
  SAVE_UP_TO: 'Save up to %s',
  FULL_STORAGE_MESSAGE: 'Your storage is full',
  PER_MONTH_LABEl: 'per month',
  BILLED_ANNUALLY: 'billed annually',
  WANT_MORE_CHECK: 'Want more? Check other',
  SUB_PLANS: 'Subscription plans',
  OTHER_SUB_PLANS: 'Other subscription plans',
  EVERYTHING_PLUS: 'Everything in Lite, plus:',
  BECOME_A_PRO: 'Become a <Pro>',
  GET_ACCESS_TO_EXCLUSIVE: 'Get access to exclusive benefits',
  WANT_MORE: 'Want more? Check other',
  FOR_ONLY: 'For only',
  UNLIMITED_MOCKUPS: '<Unlimited> high-quality mockups',
  UNLIMITED_GRAPHICS: '<Unlimited> high-quality graphics',
  BRANDING_GUIDLINE: 'Branding guideline',
  SUBSCRIBE_TO: 'Subscribe to %s',
  UNLIMITED_VIDEOS: '<Unlimited> %s videos',
  GB_STORAGE: '<%s GB Storage>',
  USED_PREMIUM_SCENES: 'You have used premium scenes in your video',
  SINGLE_HD_EXPORT: 'Single HD Export',
  YOU_DESERVE_HIGH_QUALITY: 'You deserve high-quality!',
  GET_YOUR_VIDEO: 'Get your video in <%s>',
  BUY_NOW: 'Buy Now',
  UPGRAGE_TO_GET_AVAILABLE_FONTS:
    'Upgrade to get all available fonts and premium features',
  VISUALIZER_INFO:
    'Unlimited video duration does not concern the music visualizer templates',
  STEP_COUNTER: '%s of %s',
  PLAN_FILE_SIZE_LIMIT:
    'With your current plan, you can upload no more than %s MB file. ',
  FULL_STORAGE_WARNING_TITLE: 'Sorry, your storage is full',
  FULL_STORAGE_WARNING_DESCRIPTION:
    'You can delete unused files or contact support.',
  EXPORT: 'Export',
  FILE_SIZE_BIGGER:
    'With your current plan, you can upload no more than %s MB file.',
  UPGRADE_TO_BUSINESS: 'Upgrade your plan to <Business>',
  SINGLE_UHD_EXPORT: 'Single UHD Export',
  UNLIMITED_VIDEOS_EXPORT: '<Unlimited> %s videos',
  UP_TO_EXPORT: 'up to',
  SKIP_PREMIUM_SCREENS: 'Skip Premium Scenes',
  AI_CUSTOMIZE: 'Customize',
  UNDO: 'Undo',
  REDO: 'Redo',
  ADD_NEW: 'Add new',
  PLAY_PAUSE: 'Play / Pause',
  ZOOM_IN: 'Zoom in',
  ZOOM_OUT: 'Zoom out',
  MOVE_TO_RIGHT: 'Move to right',
  MOVE_TO_LEFT: 'Move to left',
  MOVE_UP: 'Move up',
  MOVE_DOWN: 'Move down',
  GENERAL: 'General',
  PLAY: 'Play',
  TIMELINE_ZOOM: 'Timeline zoom',
  SEEK_TO_START: 'Seek to start',
  SEEK_TO_END: 'Seek to end',
  KEYBOARD_SHORTCUTS: 'Keyboard shortcuts',
  REGENERATE: 'Regenerate',
  RE_GENERATE: 'Re-Generate',
  AI_CHOICE: 'AI Choice',
  AI_EDIT: 'AI Edit',
  USE_AS_A_REFERENCE: 'Use as a reference',
  FORMAL: 'Formal',
  FRIENDLY: 'Friendly',
  INFORMATIVE: 'Informative',
  CREATIVE: 'Creative',
  MAXIMUM_SCENE_DURATION_IS: 'Maximum scene duration is %s',
  SPEAKER: 'Speaker',
  PREVIEW_SCENE: 'Preview scene',
  ALL_SCENES: 'All scenes',
  PREVIEW_SELECTED_SCENE: 'Preview selected scene',
  CANCEL_RENDERINGS: 'Cancel renderings',
  CANCEL_RENDERING: 'Cancel rendering',
  APPLY_TRANSITIONS_CHANGES_INFO_TEXT:
    'Applied transitions will be visible on all scenes after export.',
  WATERMARK_CHANGES_INFO_TEXT:
    'Watermark will be visible on all scenes after preview or export.',
  EXPORTING: 'Exporting',
  PREPARING_YOUR_MEDIA: 'Preparing your media',
  RENDERING_FINISHED_APPLYING_AUDIO: 'Rendering finished, applying audio',
  YOUR_VIDEO_IS_IN_QUEUE: 'Your video is in queue',
  EXPORT_UNLIMITED_VIDEOS_WITH_FAST_PREVIEW_TO_SAVE_TIME:
    'Export <unlimited> videos with fast preview to save time',
  AVAILABLE_CREDITS: 'Available credits: %s',
  CREDITS_AVAILABLE: '%s credits available.',
  REFILL_CREDITS: 'Refill Credits',
  REFILL_CREDITS_AI_IMAGE_GENERATOR: 'Refill Credits',
  ADD_PROMPT_OR_REFERENCE_IMAGE_TO_GENERATE: 'Add prompt to generate',
  REMOVE_OUTLINE: 'Remove outline',
  ADD_NEW_LINE: 'Add new line',
  PREMIUM_SCENE: 'Premium Scene',
  CANCEL_PREVIEW_REND_POPUP_TITLE: 'Are you sure to cancel all renderings?',
  CANCEL_PREVIEW_REND_POPUP_DESCRIPTION:
    'By canceling all renderings, any progress made will be lost.',
  YES: 'Yes',
  NO_GO_BACK: 'No, go back',
  PREVIEW_ALL_SCENES: 'Preview all scenes',
  CANCEL_SELECTED_SCENE: 'Cancel selected scene',
  CANCEL_ALL_SCENES: 'Cancel all scenes',
  FONTS: 'Fonts',
  STYLES: 'Styles',
  ADD_TEXT_TO_SPEECH: 'Add text to speech',
  UNSAVED_TTS_WARNING: `You have unsaved changes. \nDo you want to leave without generating?`,
  COMPLETED: 'Completed',
  AUDIO: 'Audio',
  COLORS: 'Colors',
  TRANSITIONS: 'Transitions',
  STYLE: 'Style',
  MY_PROJECTS: 'My projects',
  MORE: 'More',
  MY_ACCOUNT: 'My account',
  HELP_SUPPORT: 'Help & Support',
  SETTINGS: 'Settings',
  THEME: 'Theme',
  SIGN_IN: 'Sign in',
  SIGN_OUT: 'Sign out',
  GUIDE_ME: 'Guide me',
  FONT_LIBRARY: 'Font library',
  UPLOADED_FONTS: 'Uploaded fonts',
  PREVIEW_NEED_CANVAS_TEXT_MOBILE:
    'To see the final animation tap on eye icon.',
  PREVIEW_NEED_CANVAS_TEXT_DESKTOP:
    'To see the final animation click on ‘Preview’ button.',
  SEARCH_RESULTS: 'Search results',
  UPGRADE_WATERMARK_POPUP_TITLE:
    'Upgrade to add your custom watermark and enjoy other perks',
  UPGRADE_POPUP_4K_NOTICE:
    '4k export is available on templates which do support 4K.',
  CUSTOM_WATERMARKS: '<Custom> watermarks',
  UNLIMITED_4K_VIDEOS: '<Unlimited> up to 4K videos *',
  DEDICATED_ACCOUNT_MANAGER: 'Dedicated <account manager>',
  RESELLER_LICENSE: 'Reseller <license>',
  STORAGE_PER_SEAT: '<%s GB> storage per seat',
  PREMIUM_WEBSITE_PER_SEAT: '<%s premium> website(per seat)',
  MY_WATERMARK: 'My Watermark',
  ENJOY_CREATIVITY_WITHOUT_LIMITS: 'Enjoy creativity without limits',
  MIC_IS_OFF: 'Microphone is turned off',
  ENABLE_MIC_PLS: 'Please, enable sound recording in your browser settings.',
  CHANGE_FONT: 'Change Font',
  HD_720_WITH_WATERMARK: 'HD 720 with watermark',
  REMOVE_WATERMARK_POPUP_TEXT:
    'Subscribe to get high-quality videos without watermark',
  REMOVE_WATERMARK: 'Remove Watermark',
  FILL_EMPTY_AREAS_FOR_PREVIEW: 'Make some changes to preview this project',
  THIS_SCENE_CONTAINS_EMPTY_HOLDERS: 'This scene contains empty holders.',
  SCRIPT: 'Script',
  ASIAN: 'Asian',
  EUROPEAN: 'European',
  AFRO: 'Afro',
  ARABIAN: 'Arabian',
  UPGRADE_NOW: 'Upgrade now!',
  CONTACT_SUPPORT: 'Contact support!',
  SUBSCRIBED_USER_TTS_CREDIT_LIMIT: 'You have %s mins left for this month.',
  FREE_USER_TTS_CREDIT_LIMIT: 'You have %s mins left.',
  TTS_CREDIT_LIMIT_EXPIRING_WARNING: 'You have less than 1 min left.',
  TTS_UPGRADE_POPUP_TITLE: 'Upgrade to have more Text to Speech minutes',
  TTS_BUSINESS_POPUP_LIMIT: '<%s mins> of text to speech per seat / month',
  TTS_BUSINESS_POPUP_4K: 'Unlimited <Ultra HD 4K> videos',
  TTS_BUSINESS_POPUP_WATERMARK: '<Your watermark> on video',
  TTS_BUSINESS_POPUP_TEAM: '<Team> management',
  ULTRA_HD_4K_EXPORT_NOTICE:
    'Ultra HD 4k export is available on templates which do support 4K.',
  LITE_VIDEO_EXPORT_LIMIT: '<%s HD720> videos with no watermark / month',
  PREMIUM_TEMPLATES: '<Premium> templates',
  TTS_LIMIT_MINS_PER_MONTH: '<%s mins> of text to speech / month',
  UNLIMITED_FULL_HD_VIDEOS: 'Unlimited <Full HD1080> videos',
  COMMERCIAL_USE: 'Commercial use',
  PRIORITY_RENDERING: '<Priority> rendering',
  EVERYTHING_PLUS_PRO: 'Everything in Pro, plus:',
  CONTACT_SUPPORT_TO_GET_MORE: 'Contact support to get more!',
  NEED_HELP_HIRE_EXPERT: 'Need help? Hire an expert',
  NEED_HELP_HIRE_EXPERT_TOOLTIP:
    'Hire an expert to help you create your video.',
  BACK_TO_SCENES: 'Back to scenes',
  STRUGGLING_WITH_SCENES: 'Struggling with scenes?',
  LET_OUR_EXPORTS_CREATE_YOUR: 'Let our experts create your project for you!',
  SERVICE_INCLUDES_EXTRA_COSTS: '* Service includes extra costs',
  THIS_FIELD_IS_REQUIRED: 'This field is required.',
  ENTER_YOUR_EMAIL: 'Enter your email',
  TYPE_A_BRIEF_DESCRIPTION_OF_YOUR_VIDEO_NEEDS:
    'Type a brief description of your video needs',
  PLEASE_ENTER_VALID_EMAIL: 'Please enter a valid email.',
  THANK_YOU: 'Thank you!',
  WE_WILL_CONTACT_YOU:
    'Our team will contact you soon to discuss your video requirements in more detail.',
  CONTACT_US_STEP_1_TITLE: 'Provide email and video topic',
  CONTACT_US_STEP_1_DESCRIPTION:
    'Enter your email address and briefly outline your project or topic.',
  CONTACT_US_STEP_2_TITLE: 'Wait for our experts to get in touch',
  CONTACT_US_STEP_2_DESCRIPTION:
    'Our team will reach out to discuss the video scope, style and exchange files.',
  CONTACT_US_STEP_3_TITLE: 'Receive your final video',
  CONTACT_US_STEP_3_DESCRIPTION:
    'Our experts will create and deliver your completed video.',
  EDIT_AUDIO: 'Edit audio',
  VERSIONS: 'Versions',
  TRACK: 'Track',
  SECOND: 'second',
  MINUTE: 'minute',
  SECONDS: 'seconds',
  MINUTES: 'minutes',
  WEEKLY_LITE_USER_TTS_LIMIT: 'You have %s mins left for this week.',
  YOU_NEED_MORE_MINUTES: 'You need more minutes to create AI videos.',
  TTS_AI_LIMIT_TITLE: `You've reached your text to speech limit for this month.`,
  UPGRADE_TO_GET_MORE: 'Upgrade to get more!',
  SEARCH_MUSIC: 'Search music',
  SEARCH_VOICEOVER: 'Search voiceover',
  TTS_AI_LIMIT_TITLE_WEEKLY: `You've reached your text to speech limit for this week.`,
  SEE_ALL_SCENES: 'See all scenes',
  CHANGES_APPLIED: 'Changes Applied',
  TRIM: 'Trim',
  ENHANCE_SCRIPT: 'Enhance script',
  TTS_AI_LIMIT_TITLE_FREE: `You've reached your text to speech limit.`,
  OR_IMPORT_FROM: 'or import from',
  YES_DROP_HERE: 'Yes, drop here!',
  DRAG_AND_DROP_YOUR_IMAGES_HERE: 'Drag and drop your images here',
  SCAN_WITH_YOUR_PHONE_TO_UPLOAD: 'Scan with your phone to upload',
  SAVED_IN_MY_FILES: 'Your files will be saved in "My Files"',
  UPLOAD_MEDIA_FILES_TO_ACCOUNT: 'Upload media files to %s account',
  FILES: 'Files',
  TEXTS: 'Texts',
  CUSTOMIZE_TEXT: 'Customize Text',
  CONTROLS: 'Controls',
  LEAVE_PAGE_MESSAGE:
    'Are you sure you want to leave? Your changes may not be saved.',
  ADVANCED_EDITOR_POPUP_TITLE: 'Want to go to the Advanced Editor?',
  ADVANCED_EDITOR_POPUP_DESCRIPTION:
    "In this editor, you'll be able to modify the timeline, change music, add text-to-speech and more.",
  NOTE: 'Note',
  ADVANCED_EDITOR_POPUP_WARNING:
    'Once you switch to the advanced editor, your project will stay in advanced mode and can’t return.',
  GO_TO_ADVANCED_EDITOR: 'Go to Advanced Editor',
  AI_TEXT_AREA_PLACEHOLDER_SECOND:
    'Create an informative explainer video for my tech startup, simplifying how our AI-driven platform solves key industry problems.',
  AI_TEXT_AREA_PLACEHOLDER_THIRD:
    'Create a video showcasing my health coaching service, focusing on integrating balanced nutrition and active lifestyles.',
  AI_TEXT_AREA_PLACEHOLDER_FORTH:
    'Make a video to highlight the impact of my teacher training program on improving educational outcomes.',
  AI_TEXT_AREA_PLACEHOLDER_FIFTH:
    'I want a video to present how my e-commerce analytics tool boosts sales by identifying customer trends and preferences.',
  START_FROM_SCRATCH: 'Start from scratch',
  START_FROM_SCRATCH_DESCRIPTION:
    'Start creating Your project from scratch right in the editor',
  AI_IMAGE: 'AI Image',
  HISTORY: 'History',
  DEFAULT: 'Default',
  IMAGE_PROMPT_TITLE: 'Describe your image',
  IMAGE_PROMPT_PLACEHOLDER: 'Type your prompt here',
  SELECT_STYLE: 'Select style',
  GENERATING: 'Generating',
  GENERATION_LABEL: 'It may take a few seconds',
  GENERATE_SIMILAR: 'Generate similar',
  CREATE_SIMILAR: 'Create Similar',
  USE_AS_REFERENCE: 'Use as Reference',
  DOWNLOAD: 'Download',
  HISTORY_EMPTY_TITLE: 'History is empty',
  HISTORY_EMPTY_DESCRIPTION: `You don't have generated images yet`,
  ADD_REFERENCE_IMAGE: 'Add a reference image',
  ADD_REFERENCE_IMAGES_MULTIPLE: 'Add reference images <(up to %s)>',
  MODEL_REFERENCE_IMAGES_NOT_SUPPORTED:
    'This model does not support reference images.',
  MODEL_REFERENCE_IMAGE_SINGLE:
    'This model supports 1 reference image. Remove one to add another.',
  MODEL_REFERENCE_IMAGES_MULTIPLE:
    'This model supports %s reference images. Remove one to add another.',
  AI_IMAGE_LIMIT_PER_MONTH: '<%s AI images> / month',
  AI_IMAGE_UPGRADE_POPUP_TITLE: 'Upgrade to have more AI images',
  AI_IMAGE_LIMIT_SUBTITLE_FREE: `You've reached your AI image credits`,
  AI_IMAGE_LIMIT_SUBTITLE_WEEKLY: `You've reached your AI image credits for this week.`,
  AI_IMAGE_LIMIT_INFO_MONTH: `You've reached your AI image credits for this month.`,
  TERMINATED_AI_IMAGE_LIMIT: 'You have 0 credits left.',
  TERMINATED_AI_IMAGE_LIMIT_FOR_THIS_MONTH:
    'You have 0 credits left for this month.',
  WANT_CONTACT_SUPPORT: 'Want more? Contact support.',
  GENERATING_LABEL: 'Generating',
  GENERATION_MESSAGE: 'This might take a while',
  ENHANCE: 'Enhance',
  SPEAKER_GENDER: 'Speaker Gender',
  IMAGE_STYLE: 'Image Style',
  GO_BACK: 'Go Back',
  MAX_DURATION_REACHED:
    'You have reached the maximum duration of this template.',
  FREE_USERS_MAX_DURATION_REACHED:
    'Your plan allows you to create videos up to 1 minute long.',
  CREATE_EXTENDED_MUSIC_VISUALIZATION_VIDEOS:
    'Create extended music visualization videos.',
  AI_IMAGE_GENERATION_LIMIT: 'You have %s generations left.',
  AI_IMAGE_BUSINESS_POPUP_TITLE:
    'Contact support to get more AI Image credits for this month',
  TTS_BUSINESS_POPUP_TITLE:
    'Contact support to get more Text to Speech credits for this month',
  ADD_AUDIO_TO_EXPORT: 'Add audio to the empty section to export.',
  UPLOAD_MEDIA_TITLE: 'Upload your media files to get started',
  DRAG_AND_DROP: 'Drag and drop your files',
  PREVIEW_AND_EXPORT: 'Preview & Export',
  UPGRADE_TO_GET_MORE_TEXT_TO_SPEECH_CREDITS:
    'Upgrade to get more text to speech credits',
  UPGRADE_TO_GET_MORE_AI_IMAGE_CREDITS: 'Upgrade to get more AI image credits',
  UPGRADE_PLAN_TO_PREVIEW_EXPORT: 'Upgrade your plan to preview and export',
  HIGH_DEMAND_PREVIEW_EXPORT_MESSAGE:
    "We're experiencing high demand. At this time, only paid users can preview and export videos. Please try again later or upgrade to continue right away.",
  TRY_AGAIN_LATER: 'try again later',
  VOICE: 'Voice',
  SPEAKER_TOOLTIP_TEXT: 'Customizable voice tone',
  SPEAKER_TOGGLER_TOOLTIP_TEXT:
    'Select a language first to enable the voice options',
  MULTILINGUAL_LANGUAGE_TOOLTIP:
    'Multilingual is a flexible option that supports most languages, listed or not.',
  TTS_DELETE_TOOLTIP: 'Delete this Text to Speech field.',
  TTS_TEXTS_TOOLTIP:
    'Text entered here will be used to generate Text-to-Speech.',
  DEFAULT_SPEAKER: 'Default Speaker',
  DEFAULT_SPEAKER_TOOLTIP:
    'Default Speaker settings apply to all Text-to-Speech fields.',
  SPEED: 'Speed',
  CHANGE_SPEED: 'Change Speed',
  SET_VOICE_TONE: 'Set voice tone',
  SET_VOICE_TONE_TOOLTIP:
    'Select a preset tone or describe the tone for the Text-to-Speech voice.',
  FINALIZE_YOUR_VIDEO_BEFORE_GENERATING_PREVIEW:
    'Finalize your video before generating preview',
  RENDER_ANYWAY: 'Render Anyway',
  VIZUALIZER_PREVIEW_BUTTON_TOOLTIP:
    'This will generate a partial preview for you to catch the vibe.',
  VIZUALIZER_PREVIEW_BUTTON_GENERATING_STATE_TOOLTIP:
    'Generating a short preview, that may take 1-2 minutes',
  GENERATE_PREVIEW: 'Generate preview',
  GENERATING_PREVIEW: 'Generating preview',
  WATCH_PREVIEW: 'Watch preview',
  UPLOAD_MEDIA_TO_GET_STARTED_AND_ADD_A_DESCRIPTION:
    'Upload media to get started and add a description',
  UPLOAD_YOUR_MEDIA: 'Upload your media *',
  PICK_A_TOPIC_FOR_YOUR_VIDEO: 'Pick a topic for your video',
  UPLOADED_MEDIA_FILES: 'Uploaded media files',
  DESCRIBE_YOUR_VIDEO: 'Describe your video',
  TOPIC_LABEL_OTHER: 'Other',
  TOPIC_LABEL_TRIP: 'Trip',
  TOPIC_DESCRIPTION_TRIP_1: 'Exploring the streets of Barcelona.',
  TOPIC_DESCRIPTION_TRIP_2: 'Weekend getaway to the mountains.',
  TOPIC_DESCRIPTION_TRIP_3: 'Relaxing beach vacation in Bali.',
  TOPIC_DESCRIPTION_TRIP_4: 'City adventure in Tokyo, spring 2025.',
  TOPIC_DESCRIPTION_TRIP_5: 'Backpacking across Europe, summer 2025.',
  TOPIC_LABEL_CARS: 'Cars',
  TOPIC_DESCRIPTION_CARS_1: 'Cruising through scenic highways in my new car.',
  TOPIC_DESCRIPTION_CARS_2: 'Test driving the latest sports car model.',
  TOPIC_DESCRIPTION_CARS_3: 'A day at the racetrack with my car.',
  TOPIC_DESCRIPTION_CARS_4: 'My classic car restoration project.',
  TOPIC_DESCRIPTION_CARS_5: 'Speeding down the highway with my dream car.',
  TOPIC_LABEL_DRIFT: 'Drift',
  TOPIC_DESCRIPTION_DRIFT_1: 'Drifting around sharp corners at the track.',
  TOPIC_DESCRIPTION_DRIFT_2: 'Epic drift battles at the racing event.',
  TOPIC_DESCRIPTION_DRIFT_3: 'Mastering the art of drifting in my car.',
  TOPIC_DESCRIPTION_DRIFT_4:
    'Sliding through the turns, feeling the adrenaline.',
  TOPIC_DESCRIPTION_DRIFT_5: 'High-speed drift on a mountain road.',
  TOPIC_LABEL_REAL_ESTATE: 'Real Estate',
  TOPIC_DESCRIPTION_REAL_ESTATE_1: 'Touring a luxury penthouse in the city.',
  TOPIC_DESCRIPTION_REAL_ESTATE_2: 'Open house at a stunning beachside villa.',
  TOPIC_DESCRIPTION_REAL_ESTATE_3:
    'Newly listed modern home with incredible views.',
  TOPIC_DESCRIPTION_REAL_ESTATE_4:
    'Exploring a cozy, charming cottage in the countryside.',
  TOPIC_DESCRIPTION_REAL_ESTATE_5:
    'Looking for my dream home in the heart of downtown.',
  TOPIC_LABEL_PARTY: 'Party',
  TOPIC_DESCRIPTION_PARTY_1:
    'Celebrating with friends at an unforgettable party.',
  TOPIC_DESCRIPTION_PARTY_2: 'DJ spinning the beats all night long.',
  TOPIC_DESCRIPTION_PARTY_3: 'Birthday bash with amazing people and vibes.',
  TOPIC_DESCRIPTION_PARTY_4: 'Party under the stars with incredible music.',
  TOPIC_DESCRIPTION_PARTY_5: 'Dancing until dawn at the wildest party.',
  TOPIC_LABEL_BIRTHDAY: 'Birthday',
  TOPIC_DESCRIPTION_BIRTHDAY_1:
    'Surprising my best friend with a birthday party.',
  TOPIC_DESCRIPTION_BIRTHDAY_2:
    'Celebrating my milestone birthday with family.',
  TOPIC_DESCRIPTION_BIRTHDAY_3: 'The perfect birthday party surprise for Mom.',
  TOPIC_DESCRIPTION_BIRTHDAY_4:
    'A fun-filled birthday celebration with all my loved ones.',
  TOPIC_DESCRIPTION_BIRTHDAY_5: 'Making memories at my birthday dinner.',
  TOPIC_LABEL_WEDDING: 'Wedding',
  TOPIC_DESCRIPTION_WEDDING_1: 'Our dream wedding day at the beach.',
  TOPIC_DESCRIPTION_WEDDING_2: "Saying 'I do' with a view of the mountains.",
  TOPIC_DESCRIPTION_WEDDING_3: 'Celebrating love on our perfect wedding day.',
  TOPIC_DESCRIPTION_WEDDING_4:
    'The happiest day of our lives, surrounded by family.',
  TOPIC_DESCRIPTION_WEDDING_5:
    'First dance as a married couple in a beautiful garden.',
  TOPIC_LABEL_SALES: 'Sales',
  TOPIC_DESCRIPTION_SALES_1: "Black Friday deals you don't want to miss!",
  TOPIC_DESCRIPTION_SALES_2: 'Huge discounts on all our top products.',
  TOPIC_DESCRIPTION_SALES_3: 'Clearance sale: Everything must go!',
  TOPIC_DESCRIPTION_SALES_4: 'Limited-time offers on our best-selling items.',
  TOPIC_DESCRIPTION_SALES_5: 'Shop our seasonal sale and save big!',
  TOPIC_LABEL_MENU: 'Menu',
  TOPIC_DESCRIPTION_MENU_1:
    'Tasting the new seasonal dishes at the restaurant.',
  TOPIC_DESCRIPTION_MENU_2:
    'A delicious 5-course meal with fine wine pairings.',
  TOPIC_DESCRIPTION_MENU_3: 'Indulging in my favorite comfort foods tonight.',
  TOPIC_DESCRIPTION_MENU_4:
    "Exploring the chef's specials at our local bistro.",
  TOPIC_DESCRIPTION_MENU_5: 'A diverse menu with something for everyone.',
  TOPIC_LABEL_ADVENTURE: 'Adventure',
  TOPIC_DESCRIPTION_ADVENTURE_1:
    'Hiking through the rugged mountains in Alaska.',
  TOPIC_DESCRIPTION_ADVENTURE_2:
    'Zip-lining over the rainforest canopy in Costa Rica.',
  TOPIC_DESCRIPTION_ADVENTURE_3: 'Exploring the wild deserts of Morocco.',
  TOPIC_DESCRIPTION_ADVENTURE_4:
    'Climbing to the top of a towering cliff for the view.',
  TOPIC_DESCRIPTION_ADVENTURE_5: 'Camping under the stars in the wilderness.',
  GENERATE_PREVIEW_MESSAGE:
    'Click ‘Generate preview’ to get a quick vibe of your project.',
  TEMPLATES: 'Templates',
  SWITCH_TEMPLATE: 'Switch Template?',
  SWITCH_TEMPLATE_DESCRIPTION:
    'Your changes will be applied to the new template.',
  SWITCH_TEMPLATE_WARNING_TEXT:
    "<Note:> We'll keep things as consistent as possible, but a quick review after switching is a good idea.",
  SWITCH: 'Switch',
  LANDSCAPE: 'Landscape',
  PORTRAIT: 'Portrait',
  SQUARE: 'Square',
  SEE_ALL: 'See all',
  YOUTUBE_INTROS: 'Youtube Intros',
  GAMING_INTROS: 'Gaming Intros',
  _3D_LOGO_REVEALS: '3D Logo Reveals',
  MINIMAL_LOGO_REVEALS: 'Minimal Logo Reveals',
  EXPLODING_BURING_REVEALS: 'Exploding and Burning Reveals',
  PARTICLES_LOGO_REVEALS: 'Particles Logo Reveals',
  GLITCH_LOGO_REVEALS: 'Glitch Logo Reveals',
  UPLOAD_FILES_TO_START_CUSTOMIZING:
    'Upload your files to start customizing your video',
  UPLOAD_FILES_TO_PREVIEW: 'Upload your files to preview your video',
  PREMIUM_TEMPLATE_UPGRADE_POPUP_TITLE: 'Discover our premium templates',
  TUTORIAL_CANVAS_TITLE: 'Canvas',
  TUTORIAL_CANVAS_CONTENT:
    'This is your main editing area. Click on any text, image, or video to edit it directly on the canvas.',
  TUTORIAL_TIMELINE_TITLE: 'Timeline',
  TUTORIAL_TIMELINE_CONTENT:
    'Manage your video scenes here. You can reorder scenes, adjust their duration, or add new ones with just a few clicks.',
  TUTORIAL_AUDIO_TITLE: 'Audio Tab',
  TUTORIAL_AUDIO_CONTENT:
    'Add background music to your video by uploading your own track or choosing one from our music library. You can also record a voiceover directly here.',
  TUTORIAL_TTS_TITLE: 'Text to Speech',
  TUTORIAL_TTS_CONTENT:
    'Generate voiceovers for your video. Choose a language and speaker, enter your text, and generate the voiceover. It will appear on your timeline.',
  TUTORIAL_COLORS_TITLE: 'Colors',
  TUTORIAL_COLORS_CONTENT:
    'Customize the color scheme of your animation. Pick from professionally designed palettes or create your own. Preview the video to see the changes in action.',
  TUTORIAL_TRANSITIONS_TITLE: 'Transitions',
  TUTORIAL_TRANSITIONS_CONTENT:
    'Select transitions between scenes to enhance the flow of your video. To save your time, transitions will be rendered during the final export.',
  TUTORIAL_FONT_TITLE: 'Font',
  TUTORIAL_FONT_CONTENT:
    'Choose a font from our library or upload your own. Preview the video to see how it looks in the animation.',
  TUTORIAL_PLAY_TITLE: 'Play',
  TUTORIAL_PLAY_CONTENT:
    'Click "Play" to preview your video. To ensure the animation is always up to date, we render it each time you hit play-so please allow a few moments.',
  TUTORIAL_EXPORT_TITLE: 'Export',
  TUTORIAL_EXPORT_CONTENT: `Once you're happy with your video, click "Export".We'll apply the final touches and render your video in high quality.`,
  FINISH: 'Finish',
  CHANGE_SPEAKER: 'Change Speaker',
  TONE: 'Tone',
  CHANGE: 'Change',
  INACTIVE_GENERATE_BUTTON_TOOLTIP: 'Enter text to generate audio.',
  SAVE_CHANGES_ALERT_TOOLTIP: `Click 'Save' to keep your changes`,
  DESCRIBE_YOUR_VIDEO_VIBE: "Describe your video's vibe",
  ADD_ANY_TEXT_IDEAS_OR_PHRASES:
    "Add any text, ideas, or phrases, and we'll turn them into highlight words for your video.",
  EDIT_YOUR_MEDIA_TO_FIT_PERFECTLY_IN_YOUR_VIDEO:
    'Edit your media to fit perfectly in your video',
  CUSTOMIZE_YOUR_VIDEO_TEXTS: 'Customize your video texts',
  EDIT_YOUR_MEDIA: 'Edit your media',
  YOUR_VIDEO_TEXTS: 'Your video texts',
  THESE_TEXTS_WILL_APPEAR_IN_YOUR_VIDEO:
    'These texts will appear in your video. You can edit them if you like, or leave a field empty if you don’t want text.',
  YOUR_VIDEO_CLIPS: 'Your video clips',
  SEE_HOW_YOUR_MEDIA_WILL_APPEAR_IN_YOUR_FINAL_VIDEO:
    'See how your media will appear in your final video. You can drag to reorder, and easily edit or replace clips as needed.',
  REPLACE_ALL: 'Replace All',
  UPLOAD_FROM_PHONE: 'Upload from phone',
  NEW: 'New',
  SWITCH_TEMPLATE_IN_CLICK: 'Switch your template in a click',
  NEW_TEMPLATES_TAB_DESCRIPTION:
    'The new Templates tab makes it easy to browse similar styles, explore variations, and switch templates in just a few clicks.',
  SIMILAR_TEMPLATES: 'Similar Templates',
  MEDIA_UPLOAD_UNAVAILABLE: '%s images uploaded. Remove some to add more.',
  THIS_TEMPLATE_SUPPORTS_MAX_5_MEDIA_FILES:
    'This template supports max %s media files',
  UPGRADE_TO_GET_PREMIUM_VOICES: 'Upgrade to get premium voices!',
  GENERATION_FAILED: 'Generation failed',
  TTS_LANGUAGE_MISMATCH_ERROR_DESCRIPTION:
    'Your selected speaker language and text language do not match. Please choose another speaker.',
  VIDEO_GENERATION_CALCULATIONS_NOTE: 'Calculations may vary after generation.',
  CHANGE_STYLE: 'Change style',
  LOADING: 'Loading...',
  INCLUDE_AI_VOICEOVER: 'Include AI Voiceover',
  INCLUDE_AI_VOICEOVER_DESCRIPTION: 'Appears as narration in your video.',
  GENERATE_YOUR_PROJECT: 'Generate your project',
  DURATION_AND_CREDITS_WARNING:
    'Duration and credits may slightly vary after generation.',
  PREVIEW_STORYBOARD: 'Preview storyboard',
  GENERATE_VIDEO: 'Generate video',
  NON_CREDIT_OPTION: 'Looking for a non credit option?',
  NON_CREDIT_OPTION_DESCRIPTION:
    'Generate videos with professional templates - easy, fast, and AI-powered.',
  DURATION_AND_CREDITS_WARNING_MOBILE:
    'Duration & credits may vary after generation.',
  ASPECT_RATIO_SWITCH_TO: 'Switch to {name} ({ratio})?',
  ASPECT_RATIO_WIDESCREEN: 'Widescreen',
  ASPECT_RATIO_PORTRAIT: 'Portrait',
  ASPECT_RATIO_SQUARE: 'Square',
  DISABLED_AI_VOICEOVER_TOOLTIP: 'Disabled because AI Voiceover is turned off.',
  FILL_EMPTY_VIDEO_IMAGE_AREAS_FOR_PREVIEW:
    'Add image/video to the scene to preview. ',
  SCREEN_SIZE: 'Screen Size'
}
